### ISSUE TITLE
迁移库发现有点问题

### ISSUE THREAD

**Issue by kunbo-Jiang** [xlianghang/filing#1]
LinkError: WebAssembly.instantiate(): Import #33 module="env" function="a" error: global import must be a number, valid Wasm reference, or WebAssembly.Global object

**Comment by xlianghang** [comment]
我看了下微信的[wasm文档](https://developers.weixin.qq.com/miniprogram/dev/framework/performance/wasm.html)

需要使用 WXWebAssembly，并且调 `instantiate` 时需用传文件路径，欢迎 PR 哈

**Comment by jiangkunbo0928** [comment]
但是微信的wasm不支持global对象哦

**Comment by jiangkunbo0928** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/50610531/229430503-cac32b2d-f90b-431d-8ab0-f3731a0898ca.png">
这个在微信里面不支持

**Comment by jiangkunbo0928** [comment]
然后就是 发现rar文件解压csv文件会解压不出来内容。会成[object,object]
